### ISSUE TITLE
Enemy spawn attack

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#108]
when active, if the total enemy count (boss included) is less than 5, that many enemies enter the battlefield

**Comment by MoonfaceDev** [comment]
Where do the enter the battlefield? 
Do they enter immediately when other enemies die? 
Is it always active when boss in arena? 
And why is it an attack? Does it have any anticipation, active, recovery phases?
Does it change boss animation?
