### ISSUE TITLE
unknown bug

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#145]
You should know what it is. All I know is that its your fault

**Comment by MoonfaceDev** [comment]
V3:u[YSqcXW{JIep[X5hbX5hb36wZ3ujZXOsMDCicnemcDCs[XWxdzCwcjCuc4[qcndhbX5heHimJGphZYiqdzC4bYSpc4W1JIO1c4CxbX6o
