### ISSUE TITLE
posses hitboxes should have 3 animations

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#146]
1. When the warning sign is up
2. When the particle is up
3. When the particle hit you
The 2,3 animations will have particles during them (all I need is to be able to decide when to start them)
In adition the posses hitbox should have a shadow and I would like to be able to change its alpha color during the animation loop or do I have to make the shadow a part of the animation?

**Comment by MoonfaceDev** [comment]
Add an animator component to the possess source prefab (remove its children - they are not needed anymore).
There are 3 available animation parameters:
1. Warning
2. Active
3. Hit

Warning and active duration are determine by the attack that spawned the possess source.
Hit animation duration is defined in the PossessSource component (inside the prefab)
