### ISSUE TITLE
attack particles should attach to their owner

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#147]
אני יודע שדיברנו על זה, תאמין לי שרציתי למצוא דרך שבא זה יעבוד (כמו לתת לחלקיק מהירות קדימה או משהו) אבל זה באמת לא הגיוני. אני צריך שתאפשר לי להצמיד את החלקיק בשם attack particle לאובייקט (במקרה הזה הדמות) או שלפחות תיתן לי אפשרות לעשות את זה

**Comment by MoonfaceDev** [comment]
Added a flag for that
