### ISSUE TITLE
Barrier does not work

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#149]
The right barrier(and so far the only barrier) doesnt stop the player and characters from overlaping it. I am not sure if it is my fault for puting wrong numbers or yours in the code. please check his compoments before looking in the code.

**Comment by MoonfaceDev** [comment]
It's not an issue. Ask in discord

**Comment by MoonfaceDev** [comment]
But the answer is to add an empty object, add "barrier" tag, and add Hitbox component.

**Comment by MoonfaceDev** [comment]
I know there's no manual yet, but just know that you need to add a `CachedObject` component (might change in the future).
Look how I added it:
![image](https://user-images.githubusercontent.com/36325466/205755207-66f2c837-f3a3-45e7-8116-d4e0611b952a.png)
