### ISSUE TITLE
I need the following patterns and parameters

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#151]
Patterns:
1. moving to coordinates on the map (that is predecided)
2. Reposition - picking a position based on a predecided distance from the player, then moving to the decided location even if the player moved and the distance betwwen him and the location changed. For example: finding a location that is 4 meter away from the player, then going to the chosen location even if the player moved

Parameters:
1. distance from the location (if needed we can make an empty object, place it on the map and the parameter will caculate the distance from him.
2. Reposition distance (if it is posible to measure the distance from the "reposition" location).

את 1 בשניהם אני חייב, 2 אני רוצה אבל לא חייב

**Comment by MoonfaceDev** [comment]
We agreed to change pattern #2 to "pick a random direction, for a predecided duration"
