### ISSUE TITLE
attack particles are weird when spawn to get left

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#155]
![image](https://user-images.githubusercontent.com/105556437/205890815-282050f1-bdc2-421a-9939-17d6ad0380cf.png)
When I attack to the right it works perfectly

**Comment by MoonfaceDev** [comment]
This time its completely yours :)
![image](https://user-images.githubusercontent.com/36325466/206016554-27bde81f-b9da-486d-ae3d-20de8cd9ec20.png)
When you set Z to -1, it will be 1 unit near the camera when player is looking right.
But it is 1 unit FAR from the camera when player is looking left.

**Comment by Yairb27** [comment]
nope

**Comment by MoonfaceDev** [comment]
Changed rotation system to affect only X axis
