### ISSUE TITLE
When becoming possessed during an attack that include movement, angel wont stop moving

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#169]

**Comment by MoonfaceDev** [comment]
Couldn't reproduce, might have fixed already. check pls

**Comment by Yairb27** [comment]
just make sure possessed player speed is set to 0

**Comment by MoonfaceDev** [comment]
Well of course I did. There might have been a special case where it is ignored, or reset while inside possessed effect
