### ISSUE TITLE
the boss somthimes thinks angel is the center of the world

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#170]
![image](https://user-images.githubusercontent.com/105556437/206905863-fbdd9e6c-24c1-4cc9-a230-813eba4f5203.png)
After the bug with the possess attack the boss enteredtoward center pattern but decided to follow me. I know for sure he was after angel because he stoped when he reached her and followed her when she moved

**Comment by MoonfaceDev** [comment]
Couldn't reproduce

**Comment by MoonfaceDev** [comment]
I know, but I tried for a few minutes. From now on, I suggest you record your gameplays, cause sometimes I just don't manage to reproduce, and I'm not gonna kill all my free time for that :(
btw I killed the boss while trying
