### ISSUE TITLE
electric effect is behaind the player again

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#174]
why

**Comment by Yairb27** [comment]
אני לא מצליח לשחזר את זה, לא יודע

**Comment by Yairb27** [comment]
הצלחתי, אחרי שאתה סופג מכה של חשמול האפקט נוצר מאחוריך, רק כאשר אתה זז למעלה הוא עובר לליר מלפניך

**Comment by MoonfaceDev** [comment]
Fixed. From now on, the particle's movable object should have angel as parent
