### ISSUE TITLE
parry refactor 

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#231]
צריך לעשות refactor לparry.
הבעיה היא שאני כן רוצה שלפעמים הדמות תחסום מכות ולא בהכרח תתקע את האוייבים על כך, לדוגמא כשאוייב עושה משהו שאמור להרחיק את הדמות הדמות אמורה להיות יכולה להגן מכך אבל בגלל המצב הגנה מקומבו המכיל מכה משתק את האוייב (ובעתיד לשיתוק הזה השלכות נוספות). 
הפתרון שאני מציע זה להפוך את הparry למד עם מספר שלם, כל חסימת מכה מורידה ממנו אחד ומכה שלא נחסמת ממלאת אותו עד הסוף, כשהמד מתרוקן הדמות בbreak וכשנגמר הbreak המד חוזר להיות מלא. כך גם אפשר לעשות אוייבים קשוחים יותר שמחזיקים מכמד ליותר מכות. למד נקרא break thoughness

**Comment by MoonfaceDev** [comment]
Refactor done.
Consider adding UI

**Comment by Yairb27** [comment]
not for all, only on tough guys
