### ISSUE TITLE
Cave goblin Moves

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#51]
Move to player X range, NormalAttack, AltNormalAttack, Idle for X seconds.
Move to player X range, NormalAttack, AltNormalAttack, Uppercut, Idle for X seconds
Move to player X range, NormalAttack, AltNormalAttack, Uppercut, move backwards for X seconds
Move to player X range, Electric Attack, Idle for X seconds

**Comment by MoonfaceDev** [comment]
Added all patterns just for that
