### ISSUE TITLE
Goblin stand on air

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#75]
מישומה לפעמים הגובלין מחליט לעמוד על האוויר, זה קורה בעיקר שהשחקן קופץ וקרוב אליו

**Comment by Yairb27** [comment]
![image](https://user-images.githubusercontent.com/105556437/195718129-db99dd42-a079-4ebe-85c7-effbf6cf05bd.png)

**Comment by MoonfaceDev** [comment]
Fixed. It happened because of arc pattern
