### ISSUE TITLE
The countdown of max combo time should start after the recovery frames

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#97]

**Comment by MoonfaceDev** [comment]
Change you to assignee.
Think about what you want here.
If you need separate combo time for each attack, then tell me

**Comment by Yairb27** [comment]
that does not mean that you can only preform moves after the recovery frames, you frames you can preform attacks on are the recovery and the max combo time. (instant moves can also during the antisipation and active frames of interaptable moves)

**Comment by MoonfaceDev** [comment]
Done, check it out. btw, NOT A BUG
